apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: jenkins-trigger
  namespace: argo
spec:
  entrypoint: jenkins-job-trigger
  templates:
    - name: jenkins-job-trigger
      script:
        image: docker.io/greenopsinc/pygithub
        command: [/bin/bash, -c, pip install python-jenkins && python]
        source: |
          jenkins_url = 'http://192.168.64.21:32075'
          print(jenkins_url)
          jenkins_username = 'admin' #os.getenv('JENKINS_USERNAME')
          jenkins_password = '2546fd2aff054382bede4e830cb07020'
          job_name = 'wait-step'
          # token_name = os.getenv('TOKEN_NAME')

          jenkins_srv = jenkins.Jenkins(jenkins_url, username=jenkins_username, password=jenkins_password)
          next_build_number = jenkins_srv.get_job_info(job_name)['nextBuildNumber']
          jenkins_srv.build_job(job_name)#, token=token_name)

          while True:
              time.sleep(10)
              build_info = jenkins_srv.get_build_info(job_name, next_build_number)
              if build_info['result'] != None:
                  print(build_info['result'])
                  if build_info['result'] == "FAILURE":
                      sys.exit(1)
                  break
          sys.exit(0)
